source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GHImageCaching_Example', :exclusive => true do
  pod 'GHImageCaching', :path => '../'
end

target 'GHImageCaching_Tests', :exclusive => true do
  pod 'GHImageCaching', :path => '../'

  
end
