source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'GHImageCaching_Example' do
  pod 'GHImageCaching', :path => '../'
end

target 'GHImageCaching_Tests' do
  pod 'GHImageCaching', :path => '../'

  
end
